version: '3.9'

services:
  postgresql:
    image: postgres:16-alpine
    container_name: qode_postgresql
    restart: always
    environment:
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
    ports:
      - $DATABASE_PORT:$DATABASE_PORT
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - qode-network

networks:
  qode-network:
    driver: bridge

volumes:
  postgresql_data: